hooks/MinimapMesh.cpp, sections/MinimapMesh.cpp
Console command: "cam_DefaultMiniLOD 0" now completely disable mesh renderer for minimap
=> Disable mesh rendering for minimap

README.md, hooks/SetStatFix.cpp, section/SetStatFix.cpp
Returns `true` if there is no such stat to be done like this:
```lua
if unit:SetStat("a", 4) then
unit:GetStat("a", 4)
end
```
Tried to redirect to `Unit:GetStat`, didnt work for some reason...
=> Fix Unit:SetStat

README.md, hooks/ForkThreadFix.cpp, section/ForkThreadFix.cpp
`ForkThread` crashes when used with **any** of cfunction.
```lua
ForkThread(LOG, "hello!")
```
After patch it no longer accepts cfunction as fisrt argument. The valid code:
```lua
ForkThread(function(msg) LOG(msg) end, "hello!")
```
=> Forbid passing a `cfunction` into `ForkThread`

README.md, hooks/StopReclaimWhenPaused.cpp, section/StopReclaimWhenPaused.cpp
https://github.com/FAForever/fa/issues/3832
Note that reclaim animation and progress bar are `on`. Technically unit is still reclaiming (just at 0 speed), so if we want to remove animation then it should be done in lua using OnPaused/OnUnpaused callbacks.
Exe: https://mega.nz/file/oMBTFDAB#eKY_hR4IOMXysW1mXYcjml2l0nTzG0cci22U318Y-cw
=> StopReclaimWhenPaused

README.md, hooks/FixCollisions.cpp
Allows the closest collision of a projectile to be the impact when it has multiple potential collision results in a single tick.
=> Allow multiple collisions

README.md, hooks/FixCollisions.cpp
Currently, the engine calls `OnEnterWater` and `OnExitWater` on a projectile whenever its current velocity puts it past the water plane - even if it would collide with the terrain surface first. This PR moves the callbacks to after the terrain check so that they can be unscheduled when the terrain does end up being the impact result.
=> Let terrain prevent projectile layer change callbacks

README.md, hooks/FixCollisions.cpp
The collision line projectiles use for units is shifted backwards by 0.1 of the velocity. This PR removes that.
=> Measure unit collisions properly

hooks/FixCollisions.cpp
Apparently, removing the 10% entity velocity collision distance offset makes two-stage artillery shells register shield hits as terrain collisions, thus causing them to pierce through them with their sub-shells. Changing it to 1% appears to work for now.
=> Change 10% entity collision detection distance from 0% to 1%

README.md, hooks/WorldViewCustomRender.cpp, section/DrawFunc.cpp, section/WorldView.cpp, section/include/moho.h
* get worldview pointer from arguments
* use `OnRenderWorld` of the worldview
* custom world rendering works when `SetCustomRendering` is set to true
Example:
```lua
viewLeft.OnRenderWorld = function(self, delta)
UI_DrawCircle(GetMouseWorldPos(), 10, 'ffffffff', 0.3)
end
viewLeft:SetCustomRender(true)
```
=> Fix custom world rendering feature

hooks/IntelUpdate.cpp
Currently, units only update the intel grid when either 30 ticks have passed or they have moved 33% of their intel radius. This PR reduces that time down to 5 ticks. This likely means that the intel radius ratio can be changed or even removed altogether, but it is currently left alone for teleportation and edge cases with mods.
=> Reduce intel update interval

README.md, section/ProjectileNewMethods.cpp, section/include/moho.h
Relates to:
* [Add `GetMaxZigZag` to the projectile class FA-Binary-Patches#57](https://github.com/FAForever/FA-Binary-Patches/issues/57)
* [Add `GetZigZagFrequency` to the projectile class FA-Binary-Patches#58](https://github.com/FAForever/FA-Binary-Patches/issues/58)
* [Add `GetCurrentTargetPositionXYZ` to the projectile class FA-Binary-Patches#59](https://github.com/FAForever/FA-Binary-Patches/issues/59)
* [Add `SetNewTargetGroundXYZ` to the projectile class  FA-Binary-Patches#60](https://github.com/FAForever/FA-Binary-Patches/issues/60)
=> ProjectileNewMethods

README.md, hooks/FixGetInterpolatedAlignedBox.cpp, section/Strings.cpp
`CUIWorldMesh:GetInterpolatedAlignedBox` previously returned a table like
```
{
xMin = meshInstance->xMin
yMin = meshInstance->yMin
zMin = meshInstance->zMin
xMax = meshInstance->xMax
xMax = meshInstance->yMax // bad!
xMax = meshInstance->zMax // wrong field!
}
```
Now it correctly does
```
{
xMin = meshInstance->xMin
yMin = meshInstance->yMin
zMin = meshInstance->zMin
xMax = meshInstance->xMax
yMax = meshInstance->yMax
zMax = meshInstance->zMax
}
```
=> Fix `CUIWorldMesh:GetInterpolatedAlignedBox` return value

README.md, section/GetHighlightCommand.cpp, section/SimGetCommandQueue.cpp, section/include/moho.h
Resolves #51 
``UI_Lua ForkThread(function() while true do local a = GetHighlightCommand() if a then WARN(repr(a)) end WaitSeconds(1) end end)``
=> GetHighlightCommand

README.md, hooks/FixTestCommandCaps.cpp
`Unit:TestCommandCaps` and `Unit:TestToggleCaps` current both check the blueprint's `General.ToggleCaps` - this patch fixes that so that testing command caps correctly checks `General.CommandCaps`. Updates the README for better organization.
=> Fix Test Command Caps and update readme

README.md, hooks/EnableConsoleCommands.cpp
Adds the following console commands:
* `ren_Steering`
* `dbg_Ballistics` 
* `dbg_CollisionBeam`
* `dbg_EfxBeams`
* `dbg_Projectile`
* `dbg_Trail`
=> Enable unused console commands

README.md, hooks/RemoveTransportLoadFactor.cpp
There was lingering code in the engine to calculate the "transport load factor" (how much the transport slows down given the weight of the units inside) when an aircraft first moves - this was causing issues with some survival maps that spawn transports with units inside now that we've change the `AverageDensity` blueprint value of units. This PR makes the load factor always return `1.0`.
=> Remove transport load factor

README.md, hooks/Class4AttachSize.cpp
The engine is missing a break in a switch-case statement that makes class 4 attach points get overridden by class special attach points by fall-through - this PR adds the break.
=> Enable class 4 attach points

README.md, hooks/Class4AttachSize.cpp
Reverts FAForever/FA-Binary-Patches#80
Survival maps rely on the ability to attach experimental units to transports. This change breaks that behavior. It is technically correct, but given the nature of FAForever we're going with what has worked so far and therefore we revert this change.
=> Revert "Enable class 4 attach points"

README.md, hooks/TableInsertFix.cpp
Replaces `LuaObject::Insert` with `LuaObject::SetObject`. `LuaObject::Insert` implementation uses global access to `table.insert`, which can be very expensive, in addition it does this every time. `LuaObject::SetObject` is equivalent to `t[n] = o` syntax. 
```
UI_Lua local _ti = table.insert local i = 1 local s =  GetSelectedUnits() or {} _G.table.insert = function(... )  LOG(i) i = i + 1 return  _ti(unpack(arg)) end  EntityCategoryFilterDown(categories.COMMAND,s)  _G.table.insert = _ti
UI_Lua local _ti = table.insert local i = 1 local s =  GetSelectedUnits() or {} _G.table.insert = function(... )  LOG(i) i = i + 1 return  _ti(unpack(arg)) end  EntityCategoryFilterOut(categories.COMMAND,s)  _G.table.insert = _ti
```
These commands before patch will produce logging into console when units …
=> Replace `LuaObject::Insert` with `LuaObject::SetObject`

section/include/global.h
Based on dtor of `string` (0x00402370) and `wstring` (0x00431390).
=> Add destructor for `basic_string` implementation

README.md, hooks/BuildTemplateSnap.cpp, section/BuildTemplateSnap.cpp
Removes check of active build templates to allow snapping to resouce locations. Corresponding issue: https://github.com/FAForever/FA-Binary-Patches/issues/28 .
Template snapping applies only for mass extractors. Buildmode must start with mass extractor in order to snap.
Testing:
Create template **starting** with mass extractor. It must properly snap to mass locations.
Note: if you create template that isn't started with mass extractor it won't snap
As said: hydrocarbon templates don't snap, but hydro itself does.
=> Mass extractor template snapping

README.md, hooks/SiloProgress.cpp, section/SiloProgress.cpp
Changes how silos process their build progress (make it float instead of integer). Before this patch silos would not change their progress if they get insufficient resources, which can mislead players in understanding how economy works in game in general.
=> Silo progress fix

README.md, hooks/OnWindowMessage.cpp, section/OnWindowMessage.cpp
Adds the ability to bind the side mouse buttons (XButton1 and XButton2).
Requires changes in the lua repository
=> Adds the ability to bind the side mouse buttons

section/GiveNukeSiloAmmo.cpp
https://github.com/FAForever/FA-Binary-Patches/pull/92 introduced fix for silos that made them more viable with no resources in storages. However there was a fix that allowed to set progress to silo. And it was missed change. This PR makes this change (But in future there will be proper way to set it with C++). For now it only requires this change.
* Launch a game with ally AI and cheats
* Load a nuke to some progress
* Give to AI
* Builing progress must be set
=> Fix `SiloGiveAmmo` extension

include/LuaAPI.h, include/global.h, section/ForkThreadFix.cpp, section/ForkThreadFix.cxx, section/Lua/Iterators/IPairs.cxx, section/Lua/Iterators/IPairs.h, section/Lua/Iterators/Pairs.cxx, section/Lua/Iterators/Pairs.h, section/Lua/LuaObject.cxx, section/Lua/TableFuncs.cxx, section/Lua/TableFuncs.h, section/WorldView.cpp
* replicates various methods of LuaObject
* introduces Pairs and IPairs iterators as alternative to LuaTableIterator used by LuaPlus
=> LuaPlus replication: LuaObject

section/DrawFunc.cpp
Flush all drawn stuff only in the end of `OnRenderWorld`. That greatly improves framerate when there are thousands of lines drawn with `UI_DrawLine`.
=> Flush batcher only in the end
